name: Haxball Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot-1:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "1"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-2:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "2"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-3:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "3"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-4:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "4"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-5:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "5"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-6:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "6"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-7:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "7"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-8:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "8"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-9:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "9"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-10:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "10"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-11:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "11"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-12:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "12"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-13:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "13"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-14:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "14"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-15:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "15"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-16:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "16"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-17:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "17"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js

  run-bot-18:
    runs-on: ubuntu-latest
    env:
      JOB_ID: "18"
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=FWpzgqVJx_M"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node botsstefano.js
