name: Haxball Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        job_id: [soygoat, elmaspro, xDarkLord, pepe123, kingofball, matecrazy, lucax, anonimo77, haxkiller, julix, n0mames, trickshot, uruflow, croissant, crackdelhax, nekobot, luchito, n4styplayer, sniperxl, elprofex, maximo10, urruGOD, panconqueso, lechat, frenchball, zetax, xPepeee, totoGOAT, myst1k, phantomhax, prodel14, eltaljuan, charruaboy, darksoy, superpaton, yolow, manu88, elrekt, xuruguay, alexplayz, chivito, santiHax, momoXD, bocachancla, fulboMaster, haxwarrior, r4taPlayer, sopadebot, batataking, lebronHax, goldeoro, elqueficha, soloPro, yononabo, cr7XD, sneakyBoy, magohax, urufierro, elcapo999, carlinhos, soyAnonimo, quebola23, flamaX, elbaron, tukiMaster, nohackjustpro, papiflow, megachad, sangrepura, botkiller, ultragod, misterX, guachoPro, eltridente, martinHax, elCapi, ninjahax, pizzaboy, papanuelox, haxLife, soyyoXD, brujo33, robanick, crackB0t, d10shax, pechoFrio, lagman, sinmanos, hardcarry, jorg3pro, nolookpass, godricx, justiciaBot, ratadelgol, campeon2025, pulgahax, kylian777, jeanlecroissant, mishaxito, xdMaster, sinTeam, glitchx, parisino, cabecita, botDeFe]
        
    env:
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=_IPfyy153Ak"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
