name: La concha de tu madre

on:
  workflow_dispatch:

jobs:
  run-batch:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        batch: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and rebuild native modules
        run: |
          npm cache clean --force # Clear the npm cache to ensure fresh downloads
          npm install --unsafe-perm # Install dependencies, allowing unsafe permissions for native module compilation
          npm rebuild @koush/wrtc # Explicitly rebuild the wrtc module

      - name: Run bots batch ${{ matrix.batch }}
        env:
          SALA: 'https://www.haxball.com/play?c=6Lf-FlyeMpg'
          NOMBRE_BASE: "Satias Muarez"
          MENSAJE: "Easy for sati"
          CANTIDAD_BOTS: 7
          BATCH_NUMBER: ${{ matrix.batch }}
        run: |
          START=$(( (BATCH_NUMBER - 1) * CANTIDAD_BOTS + 1 ))
          END=$(( BATCH_NUMBER * CANTIDAD_BOTS ))
          echo "Ejecutando bots del $START al $END"
          node index.js $START $END
