name: 200 bots

on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        job_id: [perro, caca, pan, soygoat, maxiloco, xThunder, negritox, tofu, pancito, killer3000, mirage, lechuga, takatak, tosty, rulitos, 7warlord, luci4no, rexito, elpibe, nachoringa, trukini, mangote, ricopollo, jorgito, miniwilly, dr4x, zapatilla, moco, elpatron, ninja_flaco, zonito, nachofrito, crackerman, 33diesel, qwerty, hdp123, papifacha, xJose, alfajor3d, macanudo, churro, garompaX, timoteo, robinho, gus_fraba, billyboom, pepitor, doguito, papucho, mari4no, rodriluz, julitor, chasquibum, ramit0, nachogo, potaxie, tremendoXD, pancrack, fufurufo, alexkiller, donpipo, chetote, peludox, vinito, sergitox, galletin, pablitox, tonygamer, frijolito, elnono, jerecapo, tortuninja, papaos, cebollin, camaronxd, eltirri, zorrito7, diegardo, tr1p, oreja69, tomatev2, reloaded99, elpollorun, fitito, lapostaxx, juampis, trusken, guasón7, jaimeloko, fedechu, pavote, mentita, caripela, pepeflash, rudolf69, nachakoala, soplamoco, gameruco, crakerzin, hornerito, sarnita, juicyjoe, turritoX, patatronic, warloco, flautin, bardo101, capirossi, elyakuza, nashu2k, zombitu, pimpocho, chelinho, zapoide, sinverguen, cocotera, manoloX, frula77, sebaRush, punzopunz, rodrix69, fastox, mambito, fierita1, tatoman, patylu, floripon, damonio, choryXD, tutu_facha, luishon, bomberxD, marulito, totopet, elviscito, pechuga69, elgabi, pocho_man, yorchYT, reytacho, misterchan, tiogordo, andresito, ramonovich, tostadin, torta99, hugoloco, nacho_kun, cositaxd, pato_demon, ricaxd, cotorrito, cafetron, locoxav, mateoelpiola, pepeking, martyz, jorg3r, m3loco, betunator, chingonax, rulote, galletus, n3ne, bombolito, yeyo, sebitokun, doguitoPro, quemandofierro, tomyzin, manucrack, ricotote, panchulez, reboXD, vaporeon98, bubufo, sapoloco, emimax, zombiegus, papitodulce, eltopo, yuyinXD, piolator69, bobmeme, cachulin, cap00, federock, gustitoX, malulo, firulax, raulucho, minihood, mafeboy, roncoXD, javybomb, neonpaco, cuakilord, turbinaHD, juanrip, nachoBoom, gallega, tanitox, camiXP, pulgoso7, elsoñador, ramsito, fachaMix]
        
    env:
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=bxHMGH-LDzk"
      MENSAJE: "Raideados por Stefano365P"
      LLAMAR_ADMIN: "!llamaradmin gays"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
