name: buscojugs

on:
  push:            # Ejecutar cuando hay un push
    branches: [main]
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub
jobs:
  build:
    runs-on: ubuntu-latest # This is the Linux environment
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install # This command is crucial!
    - name: Run your bot
      run: node host.js
