name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
          "thr1.AAAAAGhynlAV7SZjKF7hhg.RpZO3DfTIQg",
          "thr1.AAAAAGhyo__UEml6eRkscQ.ygkJN_ajbjg",
          "thr1.AAAAAGhypBLOH0KGra7C2w.6Vw3wJobtSg",
          "thr1.AAAAAGhypByXa4gKt043Ew.aTPOAv-CSyM",
          "thr1.AAAAAGhyo-vBrBdBWFXFPw.5pZ9YJyF-sk",
          "thr1.AAAAAGhynb8woguswYJ_5g.unapv5IXHn8",
          "thr1.AAAAAGhwHnZzto2PVs_GKw.qrcFyIeTOzk",
          "thr1.AAAAAGhwILhulAS8FGdG3g.NeqMSQ_fxaQ",
          "thr1.AAAAAGhyoDlljGlfxGrjhA.qGfgSudOc20",
          "thr1.AAAAAGhyoF-hPZlB4Y4lDA.7uxl1FPU93A",
          "thr1.AAAAAGhyoHTKbnZGtvDfDw.FADZHh0Zfjo"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
